- name: Redis installation
  hosts: redis
  become: yes
  tasks:
  - name: insatall rpm
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
  - name: enable redis 6.2
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
  - name: install redis
    ansible.builtin.yum:
      name: redis
      state: installed
  
